# Generated by Django 3.1.4 on 2021-01-30 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='processedmetadata',
            name='encoder',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='processedmetadata',
            name='normalizer',
            field=models.JSONField(default=dict),
        ),
    ]
