# Generated by Django 3.1.4 on 2021-01-30 11:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('processing', '0002_auto_20210130_0707'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(upload_to='./static/upload')),
                ('title', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('type_of', models.CharField(max_length=50)),
                ('fileinfo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='processing.fileinfo')),
            ],
        ),
    ]
